on: pull_request
name: PR
jobs:
  gitHubActionForNpm:
    name: GitHub Action for npm
    runs-on: ubuntu-latest
    steps:
			- uses: actions/checkout@v1
			- name: Type checking
			- uses: actions/setup-node@v1
				with:
					node-version: '10.x'
			- run: npm install
			- run: npm run type-check
